[PR] 상품 리뷰 CRUD & 별점넣기 개발
wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend pull request #10
Opened 2023-08-29 06:44 UTC by kkkkcccchhhh

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ x ] 기능 추가
- [ x ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성

> 리뷰&별점기능을 이용하며 댓글과 별 평점을 남기고 싶은 이용자들을 위하여 개발하였습니다

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성

> 유저들이 리뷰와 별점기능을 남김으로써 다른 유저들에게 제품에 대한 별점과 리뷰를 보고 정보를 공유 할수 있도록 함으로써,
제품에 대해 실제 사용정보를 알리고 싶은 사람과,알고 싶은 사람들이 상호작용을 하여 도움이 될 수 있습니다.

<br />

- ### **리뷰 라우츠**

<img width="585" alt="image" src="https://github.com/wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend/assets/130543414/cf83acdb-3a42-48c6-8bcc-763cb51df782">

- ### **리뷰 컨트롤러**

<img width="584" alt="image" src="https://github.com/wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend/assets/130543414/745f6726-c6fa-44db-ba2b-65cf63e31ae0">

<img width="595" alt="image" src="https://github.com/wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend/assets/130543414/7518184b-7ef4-4e55-b813-9cb0d31d4853">

- ### **리뷰 서비스**

<img width="581" alt="image" src="https://github.com/wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend/assets/130543414/7a54664b-bc33-4e84-938a-ef2d2aa6e8ea">

- ### **리뷰 다오**

<img width="579" alt="image" src="https://github.com/wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend/assets/130543414/884135bf-3c3c-48de-b151-1a036ec88736">

<img width="589" alt="image" src="https://github.com/wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend/assets/130543414/9de83c3b-4ec2-4c42-b888-b9ee773a69e2">

<br />

## :: 기타 질문 및 특이 사항

> 질문 없습니다.

2023-08-29 09:29 UTC, KIMMANGYU2023 commented on src/controllers/reviewsController.js
> +const reviewModify = async (req, res) => {
- 이전 리뷰 내용 확인하여 수정하여줒세요!

2023-08-29 09:29 UTC, KIMMANGYU2023 commented on src/routes/postScrapsRouter.js
> +postScrapsRouter.post("/scrapOn", loginRequired, postScrapsController.postScrapOn);
- RESTful 한 엔드포인트 설계법에는 동사형태의 용어, 그리고 대문자 사용을 지양합니다. 해당 내용 수정하여주세요.

2023-08-29 13:35 UTC, kkkkcccchhhh commented on src/controllers/reviewsController.js
> +const reviewModify = async (req, res) => {
수정완료!

2023-08-29 13:35 UTC, kkkkcccchhhh commented on src/routes/postScrapsRouter.js
> +postScrapsRouter.post("/scrapOn", loginRequired, postScrapsController.postScrapOn);
수정완료!

2023-08-29 15:38 UTC, kyeongraekim requested changes
해당 브랜치는 Review 와 관련된 전체 레이어드 패턴 흐름의 소스코드 내역만을 품고 있어야 합니다.
scrap 과 관련된 내용은 해당 브랜치에서 없애주세요.

2023-08-30 03:43 UTC, kkkkcccchhhh commented
scrap 관련 내용 삭제 완료했습니다!

2023-08-30 05:22 UTC, kkkkcccchhhh commented
conflict 수정 완료해서 다시 올렸습니다.

2023-08-30 08:51 UTC, kyeongraekim commented
창현님 git pull origin main 이후에 최신 코드를 유지하면서 창현님의 신규코드가 합쳐져야 합니다. 현재 remote repository의 main을 담아내지 못하는 브랜치를 푸시해주셨네요!

2023-08-31 05:58 UTC, kyeongraekim commented
방금 머지된 내용이 반영된 사항으로 리뷰 내용을 추가해주셔서 푸시해주세요!

2023-08-31 06:23 UTC, kkkkcccchhhh commented
수정 완료 했습니다!

2023-08-31 06:26 UTC, kyeongraekim requested changes

2023-08-31 06:26 UTC, kyeongraekim commented on src/routes/reviewsRouter.js
> +);
- RESTful 한 엔드포인트 설계에는, 동사의 단어를 사용하지 않습니다.
- 해당 내용은 http 메소드의 의미로 충분히 대응 가능하니 모든 동적인 영어단어를 일괄 삭제해주시고, 이후에는 명사형의 데이터 리소스가 올 수 있도록 설정하여주세요,.

2023-08-31 06:56 UTC, kyeongraekim approved these changes

2023-08-31 06:56 UTC, merged