[김시연] product detail 기능 구현
wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend pull request #12
Opened 2023-08-30 04:31 UTC by hhanii

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
<img width="1331" alt="스크린샷 2023-08-30 오후 1 30 32" src="https://github.com/wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend/assets/37923273/987840d8-33fc-4422-9fc7-b474a16005ff">

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-08-30 09:00 UTC, kyeongraekim requested changes

2023-08-30 09:00 UTC, kyeongraekim commented on src/controllers/productsControllers.js
> +  console.log(categoryId);
- 불필요한 콘솔로깅을 삭제해주세요!

2023-08-30 09:00 UTC, kyeongraekim commented on src/routes/cart.router.js
> +cartRouter.delete("/deleteCart", loginRequired, cartController.deleteCart);
- insert와 delete의 개념은 post와 delete라는 http 메소드의 이미 의미적으로 충분히 표현되어 있습니다.
- 해당 내용을 RESTful 한 엔드포인트 설계법에 맞게, cart라는 명사형태만 남기고 삭제해주세요!

2023-08-30 09:03 UTC, kyeongraekim commented
이미 머지된 장바구니 코드가 함께 올라와서 다소 아쉽네요!~

2023-08-30 09:36 UTC, hhanii commented
> 이미 머지된 장바구니 코드가 함께 올라와서 다소 아쉽네요!~
ㅠㅡㅠ

2023-08-30 09:46 UTC, hhanii commented
멘토님 근데 저 체크아웃된거 모루고 여기서 푸쉬했는데 어떡해여 어떡해여 어떡해여..

2023-08-30 09:47 UTC, hhanii commented
> 멘토님 근데 저 체크아웃된거 모루고 카트에서 푸쉬했는데 어떡해여 어떡해여 어떡해여..

2023-08-31 03:22 UTC, kyeongraekim approved these changes

2023-08-31 03:22 UTC, merged