[김만규] 제품 리스트 데이터 가져오기
wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend pull request #7
Opened 2023-08-28 06:16 UTC by KIMMANGYU2023

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
모든 제품 리스트 정보 가져오기
특정 이름 제품 리스트 정보 가져오기

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
<img width="350" alt="스크린샷 2023-08-28 오후 3 15 30" src="https://github.com/wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend/assets/123226237/2805bf30-9d42-48e1-a5e4-a0127c9e6516">
<img width="725" alt="스크린샷 2023-08-28 오후 3 15 44" src="https://github.com/wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend/assets/123226237/88b5e250-c163-4829-8bec-fbf483f1ccf0">
<img width="725" alt="스크린샷 2023-08-28 오후 3 16 01" src="https://github.com/wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend/assets/123226237/f9687808-dc53-4aa6-838f-b8fdbc4e7f08">

3. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
5. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-08-28 08:25 UTC, kyeongraekim requested changes

2023-08-28 08:25 UTC, kyeongraekim commented on src/controllers/products.Controllers.js
> +    } catch (error) {
- 해당내용은 기존에 전달드린 catchAsync wrapper함수를 이용한 방법을 이용하여주세요!
- 현재 error를 잡지만 아무런 행위가 catch block에 정의되어 있지 않고, 해당 내용을 next 를 이용하여 다음함수로 전달하는 다소 불필요한 중복행위로 보여집니다.

2023-08-28 08:25 UTC, kyeongraekim commented on src/controllers/products.Controllers.js
> +    } catch (error) {
이부분도 마찬가지입니다~

2023-08-28 08:25 UTC, kyeongraekim commented on src/models/productsDao.js
> +    const products = await AppDataSource.query(`SELECT p.*, pc.name as category_name, pi.image_url
- SELECT 문에서 *사용을 지양해주시고, 상품을 조회할 떄 필요한 모든 컬럼 명을 명시하여주세요.
- 제 3의 개발자가 함께 확인할 해당 DAO 문에서 어떤 데이터를 끌고 오는지 Application 레벨에서 확인하기 위한 용입니다.

2023-08-28 08:25 UTC, kyeongraekim commented on src/routes/productsRoutes.js
> +router.get('/byName/:categoryName', async (req, res) => {
- 이름과 카테고리네임은 path paraemeter가 아니라, query string으로 받아내어서 내부에서 활용해주세요!

2023-08-28 08:25 UTC, kyeongraekim commented on src/services/productsServices.js
> +const categoryService = async (categoryId, offset, limit, minPrice, maxPrice, sortBy) => {
- 이곳은 예제코드로 드렸던 케이스에서 활용되었던 categoryService 가아닌, productService로 변경하여주세요!

2023-08-29 03:23 UTC, kyeongraekim requested changes

2023-08-29 03:23 UTC, kyeongraekim commented on src/controllers/products.Controllers.js
> +module.exports = {getProductsByCategoryId, getProducts};
- catchAsync로 쌓여진 컨트롤러 모듈에는 try-catch의 역할이 불필요해집니다.
-try-catch의 catch 블록 내 코드가 catchAsync의 역할을 뺏어가는 코드 기획이오니 해당 내용을 제거하여주세요!

2023-08-29 09:31 UTC, fierceCry commented on src/routes/productsRoutes.js
> +      req.params.categoryId = categoryId;
- 전체 내용은 controller에서 보일법한 코드 흐름입니다. 라우팅의 기능에만 입각하여 작동하는 Route 파일을 유지하여주세요!

2023-08-29 09:31 UTC, KIMMANGYU2023 commented on src/routes/productsRoutes.js
> +      req.params.categoryId = categoryId;
- 네 알겠습니다!

2023-08-29 09:32 UTC, KIMMANGYU2023 commented on src/services/productsServices.js
> +
- 다른 예제코드의 상황속에서 적용될 법한 해당 소스코드는 삭제하여주세요!

2023-08-29 15:34 UTC, closed without merging