[PR] Post & Product Scrap 기능 개발
wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend pull request #9
Opened 2023-08-29 05:49 UTC by kkkkcccchhhh

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ x ] 기능 추가
- [ x ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성

> 오늘의집을 이용하며 제품과 게시글을 스크랩 하고 싶은 싶은 이용자들을 위하여 개발하였습니다.

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성

> 유저들이 스크랩을 이용하며 내가 저장 하고 싶은 제품이나 게시글을 스크랩하여 기록 할 수 있고,
유저들의 정보를 스크랩을 하였기에 빠르게 찾아 볼 수 있도록 편리함을 줄 수 있습니다.

<br />

## :: 테스트 결과 이미지

- **포스트 스크랩 라우츠**
- **routes에서 토큰 값을 이용하여 로그인한 유저들만 스크랩 기능을 이용할 수 있는 기능을 넣어 주었습니다.**
<img width="691" alt="image" src="https://github.com/wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend/assets/130543414/33925917-b103-4d16-88cb-1b0d794629d2">

- **포스트 스크랩 컨트롤러**

<img width="565" alt="image" src="https://github.com/wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend/assets/130543414/41e9a545-5626-494c-97cb-8945d25a76e9">

- **포스트 스크랩 서비스**

<img width="543" alt="image" src="https://github.com/wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend/assets/130543414/93f2a4a1-124b-4b67-99d8-c0541f5d0073">

- **포스트 스크랩 다오**

<img width="450" alt="image" src="https://github.com/wecode-bootcamp-korea/48-2nd-Buster_Hot6-backend/assets/130543414/6d7c8853-18bb-43e7-a184-1d7e3f4bd157">

- ### **포스트 스크랩과 프로덕트 스크랩의 코드가 동일 하기 때문에 포스트 스크랩 이미지를 첨부 하였습니다.**

<br />

## :: 기타 질문 및 특이 사항
- 질문 없습니다.

2023-08-29 09:26 UTC, KIMMANGYU2023 commented on src/controllers/productScrapsController.js
> +const productScrapon = async ( req, res ) =>{
- 함수 모듈의 변수명은 getProduct, createProduct 등과 같이 동사 + 목적어 형태의 기능으로 이루어져야 합니다.

2023-08-29 09:26 UTC, KIMMANGYU2023 commented on src/controllers/productScrapsController.js
> +const productScrapoff = async ( req, res ) =>{
- 해당 내용도 마찬가지입니다.

2023-08-29 09:26 UTC, KIMMANGYU2023 commented on src/models/postScrapsDao.js
> +};
- 전체적으로 try-catch 문을 model 선에서 추가하여주세요!

2023-08-29 12:03 UTC, kkkkcccchhhh commented on src/controllers/productScrapsController.js
> +const productScrapon = async ( req, res ) =>{
수정완료!

2023-08-29 12:03 UTC, kkkkcccchhhh commented on src/controllers/productScrapsController.js
> +const productScrapoff = async ( req, res ) =>{
수정완료!

2023-08-29 12:03 UTC, ChangHyun92 commented on src/models/postScrapsDao.js
> +};
수정완료!

2023-08-29 15:36 UTC, kyeongraekim requested changes
전체적으로 Layered Pattern이 postScrap - productScrap으로 나뉘어져있습니다. Scrap은 게시글과 상품 레이어드 패턴의 하부 영역으로 들어갈 수 있게, postController, productController 패턴 내부에 녹아들 수 있게 전체적인 파일명, 디렉토리 명을 수정하여주세요!

2023-08-29 15:36 UTC, kyeongraekim commented on src/models/dataSource.js
> +  database: process.env.DB_DATABASE
- 해당 내용, 어느 키값이 맞는 것인지 팀 내 선정 내용을 따져보고 수정, 혹은 코멘트를 남겨주세요.

2023-08-29 15:36 UTC, kyeongraekim commented on src/routes/index.js
> +routes.use("/productScrap", productScrapsRouter);
- RESTful 엔드포인트 설계법에서 camelCase를 쓰지 않습니다.
- 해당 내용은 - 하이픈으로 이어주는 의미구분자를 사용해주세요.

2023-08-30 04:11 UTC, kkkkcccchhhh commented on src/models/dataSource.js
> +  database: process.env.DB_DATABASE
DB_DATABASE 가 맞습니다!

2023-08-30 04:39 UTC, kkkkcccchhhh commented on src/routes/index.js
> +routes.use("/productScrap", productScrapsRouter);
확인 했습니다 수정완료!

2023-08-30 09:03 UTC, kyeongraekim commented
이곳도 컨플릭트가 온전히 해결되지 않았습니다!~

2023-08-30 10:53 UTC, kkkkcccchhhh commented
수정 다시 완료 했습니다 죄송합니다 경래님..!

2023-08-31 05:16 UTC, kkkkcccchhhh commented
머지 해주시면 감사하겠습니다!

2023-08-31 05:42 UTC, kyeongraekim approved these changes
LGTM!~

2023-08-31 05:42 UTC, merged